spring.application.name=verificationApp
spring.profiles.default=local

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.dir=${UPLOAD_DIR:C:/uploads/}

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false

# Google Vision - PRIMARY
google.credentials.path=${GOOGLE_APPLICATION_CREDENTIALS:}

# Azure Computer Vision - FALLBACK
azure.vision.endpoint=${AZURE_VISION_ENDPOINT:}
azure.vision.key=${AZURE_VISION_KEY:}